<a href="https://colab.research.google.com/github/Sathyarajpalle/NLP-practice/blob/main/Word_Embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
import tensorflow as tf
print("Tensorflow version:", tf.__version__)
print("GPU is", "available" if tf.config.list_physical_devices("GPU") else "not available")


Tensorflow version: 2.20.0
GPU is available


In [66]:
from tensorflow.keras.preprocessing.text import one_hot

In [67]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [68]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [69]:
###vocubulary size
voc_size=500

**One hot representation**

In [70]:
onehot_repr=[one_hot(words,voc_size)for words in sent] ##These basically works and gives as index numbers
print(onehot_repr)

[[444, 112, 416, 310], [444, 112, 416, 55], [444, 462, 416, 447], [151, 119, 176, 132, 210], [151, 119, 176, 132, 60], [149, 444, 5, 416, 332], [389, 104, 157, 132]]


**Word Embedding Representation**

In [71]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [72]:
import numpy as np

In [73]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 444 112 416 310]
 [  0   0   0   0 444 112 416  55]
 [  0   0   0   0 444 462 416 447]
 [  0   0   0 151 119 176 132 210]
 [  0   0   0 151 119 176 132  60]
 [  0   0   0 149 444   5 416 332]
 [  0   0   0   0 389 104 157 132]]


In [74]:
## 10 feature dimesnions
dim=10


In [75]:
model=Sequential()
model.add(Embedding(input_dim = voc_size,output_dim = 10,input_shape = (sent_length,)))
model.compile(optimizer='adam',loss='mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:103: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [76]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ (None, 8, 10)          │         5,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [77]:
embedded_docs[0]

array([  0,   0,   0,   0, 444, 112, 416, 310], dtype=int32)

In [78]:
model.predict(np.expand_dims(embedded_docs[0],axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step


array([[[ 0.04427649, -0.03881544, -0.01748697, -0.02604628,
         -0.02589226, -0.02259788,  0.01882947, -0.0005752 ,
         -0.0357875 , -0.04400456],
        [ 0.04427649, -0.03881544, -0.01748697, -0.02604628,
         -0.02589226, -0.02259788,  0.01882947, -0.0005752 ,
         -0.0357875 , -0.04400456],
        [ 0.04427649, -0.03881544, -0.01748697, -0.02604628,
         -0.02589226, -0.02259788,  0.01882947, -0.0005752 ,
         -0.0357875 , -0.04400456],
        [ 0.04427649, -0.03881544, -0.01748697, -0.02604628,
         -0.02589226, -0.02259788,  0.01882947, -0.0005752 ,
         -0.0357875 , -0.04400456],
        [-0.0292135 ,  0.04389247,  0.01258877, -0.03567972,
          0.02601835,  0.01481995,  0.03516639, -0.03540692,
         -0.03143238,  0.04791565],
        [ 0.02190908, -0.03294491,  0.02752731, -0.02255796,
          0.04101432, -0.00266623,  0.02738314, -0.00830577,
         -0.02406722, -0.01182721],
        [ 0.02358728, -0.01856317, -0.0023964 , -0.0

In [79]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step


array([[[ 0.04427649, -0.03881544, -0.01748697, -0.02604628,
         -0.02589226, -0.02259788,  0.01882947, -0.0005752 ,
         -0.0357875 , -0.04400456],
        [ 0.04427649, -0.03881544, -0.01748697, -0.02604628,
         -0.02589226, -0.02259788,  0.01882947, -0.0005752 ,
         -0.0357875 , -0.04400456],
        [ 0.04427649, -0.03881544, -0.01748697, -0.02604628,
         -0.02589226, -0.02259788,  0.01882947, -0.0005752 ,
         -0.0357875 , -0.04400456],
        [ 0.04427649, -0.03881544, -0.01748697, -0.02604628,
         -0.02589226, -0.02259788,  0.01882947, -0.0005752 ,
         -0.0357875 , -0.04400456],
        [-0.0292135 ,  0.04389247,  0.01258877, -0.03567972,
          0.02601835,  0.01481995,  0.03516639, -0.03540692,
         -0.03143238,  0.04791565],
        [ 0.02190908, -0.03294491,  0.02752731, -0.02255796,
          0.04101432, -0.00266623,  0.02738314, -0.00830577,
         -0.02406722, -0.01182721],
        [ 0.02358728, -0.01856317, -0.0023964 , -0.0

In [80]:
sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [81]:
voc_size=500


In [82]:
[one_hot(word,voc_size)for word in sent]

[[444, 129, 186, 176, 321, 214],
 [326, 360, 186, 320, 309, 481],
 [151, 478, 108, 384],
 [444, 198, 186, 19, 444, 458],
 [314, 47, 415, 186, 320, 309, 481],
 [259, 186, 320, 309, 341, 1]]

In [85]:
import numpy as np

In [86]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 444 112 416 310]
 [  0   0   0   0 444 112 416  55]
 [  0   0   0   0 444 462 416 447]
 [  0   0   0 151 119 176 132 210]
 [  0   0   0 151 119 176 132  60]
 [  0   0   0 149 444   5 416 332]
 [  0   0   0   0 389 104 157 132]]


In [87]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [89]:
model = Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=10,input_length=8))
model.compile('adam','mse')

In [90]:
embedded_docs[0]

array([  0,   0,   0,   0, 444, 112, 416, 310], dtype=int32)

In [91]:
model.predict(np.expand_dims(embedded_docs[0],axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step


array([[[-0.00200044,  0.01146933, -0.02442888,  0.04749835,
          0.03578694,  0.00799576, -0.01306895,  0.00838299,
          0.0095352 , -0.04714772],
        [-0.00200044,  0.01146933, -0.02442888,  0.04749835,
          0.03578694,  0.00799576, -0.01306895,  0.00838299,
          0.0095352 , -0.04714772],
        [-0.00200044,  0.01146933, -0.02442888,  0.04749835,
          0.03578694,  0.00799576, -0.01306895,  0.00838299,
          0.0095352 , -0.04714772],
        [-0.00200044,  0.01146933, -0.02442888,  0.04749835,
          0.03578694,  0.00799576, -0.01306895,  0.00838299,
          0.0095352 , -0.04714772],
        [-0.00062133,  0.02241166, -0.00127835,  0.01178545,
          0.0325603 , -0.04972741,  0.04084548, -0.04430101,
          0.02347093,  0.04313557],
        [ 0.04589737, -0.00868745,  0.04529561,  0.04010024,
         -0.02463322,  0.04768134, -0.03644767, -0.04255867,
         -0.01892089, -0.03764634],
        [ 0.03986195, -0.02472017,  0.04169205,  0.0