<a href="https://colab.research.google.com/github/Sathyarajpalle/NLP-practice/blob/main/word2vec_and_avgword2vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
messages = pd.read_csv('/content/SMSSpamCollection.txt', sep='\t', names=["label", "message"])

In [2]:
messages

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [3]:
messages.shape

(5572, 2)

In [4]:
messages['message'].loc[100]

"Please don't text me anymore. I have nothing else to say."

In [5]:
#data cleaning and preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [6]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [7]:
corpus = []
for i in range(0,len(messages)):
  review = re.sub('[^a-zA-Z0-9]', ' ', messages['message'][i]) #we remove all the special character with a space using substitute function of re
  review = review.lower()
  review = review.split()
  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [8]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri 2 wkli comp win fa cup final tkt 21st may 2005 text fa 87121 receiv entri question std txt rate c appli 08452810075over18',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl 3 week word back like fun still tb ok xxx std chg send 1 50 rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press 9 copi friend callertun',
 'winner valu network custom select receivea 900 prize reward claim call 09061701461 claim code kl341 valid 12 hour',
 'mobil 11 month u r entitl updat latest colour mobil camera free call mobil updat co free 08002986030',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash 100 20 000 pound txt csh11 send 87575 cost 150p day 6day 16 tsandc appli repli hl 4 info',
 'urgent 1 week free mem

In [9]:
#creating Bag of words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500,binary = True,ngram_range=(2,2))  #binary=True makes the numbers into binary
x = cv.fit_transform(corpus).toarray()

In [10]:
x.shape

(5572, 2500)

In [11]:
y = pd.get_dummies(messages['label']).astype(int)
y = y.iloc[:,1].values

In [12]:
y

array([0, 0, 1, ..., 0, 0, 0])

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.20,random_state=0)

In [14]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(x_train,y_train)

In [15]:
y_pred = spam_detect_model.predict(x_test)

In [16]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy = accuracy_score(y_test,y_pred)

In [17]:
accuracy

0.9713004484304932

In [18]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98       955
           1       1.00      0.80      0.89       160

    accuracy                           0.97      1115
   macro avg       0.98      0.90      0.94      1115
weighted avg       0.97      0.97      0.97      1115



In [19]:
#creating the TFIDF model
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(max_features=2500,ngram_range=(1,2))
x = tv.fit_transform(corpus).toarray()

In [20]:
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [21]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.20,random_state=0)

In [22]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(x_train,y_train)

In [23]:
y_pred = spam_detect_model.predict(x_test)

In [24]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy = accuracy_score(y_test,y_pred)
accuracy

0.9811659192825112

In [25]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       955
           1       1.00      0.87      0.93       160

    accuracy                           0.98      1115
   macro avg       0.99      0.93      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [26]:
!pip install gensim

In [27]:
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')

In [28]:
wv['king']

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [29]:
wv.most_similar('man')

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.571636438369751),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116)]

In [30]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [31]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [32]:
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z0-9]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()

    review = [lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [33]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry 2 wkly comp win fa cup final tkts 21st may 2005 text fa 87121 receive entry question std txt rate c apply 08452810075over18',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling 3 week word back like fun still tb ok xxx std chgs send 1 50 rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press 9 copy friend callertune',
 'winner valued network customer selected receivea 900 prize reward claim call 09061701461 claim code kl341 valid 12 hour',
 'mobile 11 month u r entitled update latest colour mobile camera free call mobile update co free 08002986030',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash 100 20 000 pound txt csh11 send 87575 cost 150p day 6days 16 tsandcs apply reply

In [34]:
len(corpus)

5572

In [35]:
corpus[0]

'go jurong point crazy available bugis n great world la e buffet cine got amore wat'

In [36]:
from nltk.tokenize import sent_tokenize
from gensim.utils import simple_preprocess

In [37]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [38]:
words = []
# We process each message in the corpus as a single document
# instead of splitting them into sentences. This keeps the count at 5572.
for doc in corpus:
    words.append(simple_preprocess(doc))

In [39]:
words

[['go',
  'jurong',
  'point',
  'crazy',
  'available',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'wkly',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'early', 'hor', 'already', 'say'],
 ['nah', 'think', 'go', 'usf', 'life', 'around', 'though'],
 ['freemsg',
  'hey',
  'darling',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'caller',
  'press',
  'copy',
  'friend',
  'callertune'],
 ['winner',
  'valued',
  'network',
  'customer',
  'selected',
  're

In [40]:
len(words)

5572

In [41]:
import gensim

In [42]:
# Retrain the model on the updated words list
model = gensim.models.Word2Vec(words, window=5, min_count=2)
print(f"Total documents in model: {model.corpus_count}")

Total documents in model: 5572


In [43]:
model.wv.index_to_key

['call',
 'get',
 'ur',
 'gt',
 'lt',
 'go',
 'ok',
 'day',
 'free',
 'know',
 'come',
 'like',
 'good',
 'time',
 'got',
 'love',
 'text',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'going',
 'stop',
 'home',
 'lor',
 'sorry',
 'see',
 'still',
 'take',
 'mobile',
 'back',
 'da',
 'dont',
 'reply',
 'think',
 'tell',
 'week',
 'phone',
 'hi',
 'new',
 'later',
 'please',
 'pls',
 'co',
 'msg',
 'dear',
 'make',
 'night',
 'message',
 'well',
 'say',
 'min',
 'thing',
 'much',
 'hope',
 'oh',
 'claim',
 'great',
 'hey',
 'number',
 'give',
 'happy',
 'work',
 'friend',
 'wat',
 'way',
 'yes',
 'www',
 'let',
 'prize',
 'right',
 'tomorrow',
 'already',
 'said',
 'ask',
 'win',
 'amp',
 'cash',
 'life',
 'im',
 'yeah',
 'tone',
 'really',
 'babe',
 'meet',
 'find',
 'miss',
 'morning',
 'last',
 'service',
 'uk',
 'thanks',
 'care',
 'would',
 'anything',
 'com',
 'year',
 'also',
 'nokia',
 'lol',
 'every',
 'feel',
 'keep',
 'pick',
 'sure',
 'sent',
 'contact',
 'urgent',


In [44]:
model.wv['kid']

array([-0.07391566,  0.08606723,  0.05198217,  0.02278664,  0.02695585,
       -0.16542755,  0.0194768 ,  0.18269028, -0.04997925, -0.04583341,
       -0.06940499, -0.1407695 , -0.01295508,  0.06717692,  0.01069848,
       -0.08478455,  0.01041314, -0.16281386, -0.01439811, -0.19704913,
        0.04203923,  0.03136862,  0.02907159, -0.05397128, -0.03489626,
        0.00502959, -0.0847335 , -0.08735615, -0.07355721,  0.01292356,
        0.12528923,  0.0174467 ,  0.0491657 , -0.07469068, -0.02837201,
        0.10290237, -0.00509521, -0.08532295, -0.10546687, -0.15923099,
       -0.03314456, -0.08827274, -0.00550338,  0.03914999,  0.08921477,
       -0.0475568 , -0.06408001, -0.0248342 ,  0.0348197 ,  0.0776614 ,
        0.05957432, -0.10502422, -0.05490497, -0.00954154, -0.10107666,
        0.03485379,  0.07256967,  0.01422798, -0.13079193,  0.0137724 ,
        0.01499707,  0.02433871, -0.0576755 ,  0.00554316, -0.10552854,
        0.07203138,  0.04056415,  0.06403182, -0.13183628,  0.13

In [45]:
model.corpus_count

5572

In [46]:
model.epochs

5

In [47]:
model.wv.similar_by_word('kid')

[('da', 0.9975202679634094),
 ('lot', 0.9974809885025024),
 ('going', 0.9974662065505981),
 ('sure', 0.997452437877655),
 ('come', 0.9974250197410583),
 ('live', 0.9974129796028137),
 ('eat', 0.9974082708358765),
 ('next', 0.9973873496055603),
 ('end', 0.997348427772522),
 ('txt', 0.9973416328430176)]

In [48]:
model.wv.similar_by_word('happy')

[('one', 0.9994103312492371),
 ('make', 0.9993993043899536),
 ('day', 0.9993948936462402),
 ('year', 0.9993829727172852),
 ('new', 0.9993723630905151),
 ('said', 0.9993664026260376),
 ('dont', 0.9993636012077332),
 ('dear', 0.9993634819984436),
 ('would', 0.999354362487793),
 ('use', 0.9993384480476379)]

In [49]:
model.wv['kid'].shape

(100,)

In [50]:
!pip install tqdm

In [51]:
def avg_word2vec(doc):
  return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)

In [52]:
import numpy as np
from tqdm import tqdm

In [53]:
words[78]

['operate', 'lt', 'gt']

In [54]:
type(model.wv.index_to_key)

list

In [55]:
# Re-apply for the entire document set (no longer sentences)
X = []
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

  0%|          | 0/5572 [00:00<?, ?it/s]/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5572/5572 [00:00<00:00, 9234.79it/s]


In [56]:
X

[array([-0.17363282,  0.20974983,  0.10900176,  0.05413291,  0.09084468,
        -0.40934524,  0.03972912,  0.47371247, -0.1308002 , -0.11416775,
        -0.18658291, -0.37358007, -0.02232624,  0.15175724,  0.0439493 ,
        -0.22765635,  0.01588221, -0.39003062, -0.05579011, -0.47501406,
         0.09495948,  0.08589047,  0.05540874, -0.14635974, -0.09602962,
         0.00878774, -0.23006587, -0.22116946, -0.19333969,  0.05170217,
         0.29767722,  0.04071715,  0.0983996 , -0.16625424, -0.07462605,
         0.24353957, -0.03178215, -0.21983719, -0.24227752, -0.3905163 ,
        -0.08284257, -0.23972242, -0.0276648 ,  0.0947603 ,  0.21685576,
        -0.09919452, -0.15176372, -0.07567655,  0.11222147,  0.18953232,
         0.12433297, -0.2847257 , -0.11593228, -0.02233334, -0.22932373,
         0.07895967,  0.17066135,  0.02904841, -0.3162015 ,  0.03985498,
         0.05831893,  0.07573306, -0.11925924,  0.02616965, -0.27810153,
         0.18031953,  0.10627255,  0.1693778 , -0.3

In [57]:
type(X)

list

In [58]:
import numpy as np

x_new_processed = []
vector_dim = model.vector_size

for vec in X:
    if isinstance(vec, np.ndarray) and vec.shape == (vector_dim,):
        x_new_processed.append(vec)
    else:
        # Handle documents with no words found in Word2Vec vocab
        x_new_processed.append(np.zeros(vector_dim, dtype=np.float32))

x_new = np.array(x_new_processed)
print(f"Corrected Shape of x_new: {x_new.shape}")
print(f"Shape of y: {y.shape}")

Corrected Shape of x_new: (5572, 100)
Shape of y: (5572,)


In [59]:
x_new[3]

array([-0.21652997,  0.26211876,  0.13117559,  0.07409471,  0.11114994,
       -0.511442  ,  0.05394082,  0.5858838 , -0.16116053, -0.13645668,
       -0.23776104, -0.4625627 , -0.02162826,  0.18759578,  0.05285279,
       -0.28040504,  0.02073409, -0.4804492 , -0.07138921, -0.5861612 ,
        0.1214712 ,  0.10680363,  0.07314875, -0.1756047 , -0.11798962,
        0.01145076, -0.28216425, -0.27174497, -0.24262445,  0.07165054,
        0.3671539 ,  0.0468333 ,  0.12600003, -0.20950627, -0.09023508,
        0.30661803, -0.04557439, -0.2736361 , -0.30131924, -0.4838636 ,
       -0.10151049, -0.29726192, -0.03129311,  0.12119439,  0.27180827,
       -0.12849402, -0.18936783, -0.09540919,  0.13923837,  0.23786794,
        0.1556361 , -0.35999504, -0.14804512, -0.02840216, -0.2755552 ,
        0.09719679,  0.2115926 ,  0.03403264, -0.39286485,  0.04450508,
        0.07141126,  0.08795009, -0.14813296,  0.0326183 , -0.34690845,
        0.22369634,  0.13035347,  0.21723872, -0.39100173,  0.41

In [60]:
words[0]

['go',
 'jurong',
 'point',
 'crazy',
 'available',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'got',
 'amore',
 'wat']

In [61]:
x_new[0].shape

(100,)

In [62]:
print(x_new.shape)
print(y.shape)

(5572, 100)
(5572,)


In [63]:
from sklearn.model_selection import train_test_split

# Ensure we use the latest x_new and y
if len(x_new) == len(y):
    x_train, x_test, y_train, y_test = train_test_split(x_new, y, test_size=0.20, random_state=0)


In [64]:
from sklearn.ensemble import RandomForestClassifier

# Word2Vec vectors contain negative numbers, which MultinomialNB cannot handle.
# RandomForestClassifier is a better choice for continuous vector inputs.
spam_detect_model = RandomForestClassifier().fit(x_train, y_train)
print("Model training complete.")

Model training complete.


In [65]:
y_pred = spam_detect_model.predict(x_test)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print(f"Accuracy Score: {accuracy_score(y_test, y_pred)}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy Score: 0.957847533632287

Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.99      0.98       955
           1       0.96      0.74      0.83       160

    accuracy                           0.96      1115
   macro avg       0.96      0.87      0.90      1115
weighted avg       0.96      0.96      0.96      1115

